// 路徑: lib/providers/language_provider.dart
import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  String _language = 'en'; // 'en' or 'zh'
  String get language => _language;
  bool get isEnglish => _language == 'en';

  /// Returns a [Locale] object derived from the current language code.
  Locale get locale => Locale(_language);

  void toggleLanguage() {
    _language = _language == 'en' ? 'zh' : 'en';
    notifyListeners();
  }

  void setLanguage(String lang) {
    _language = lang;
    notifyListeners();
  }

  String t(String key) {
    final map = _language == 'zh' ? _zh : _en;
    return map[key] ?? key;
  }

  // ── English ────────────────────────────────────────────────
  static const Map<String, String> _en = {
    // App
    'app_title': 'EduLearn',
    'welcome': 'Welcome back,',
    'language': 'Language',

    // Auth
    'login': 'Login',
    'logout': 'Logout',
    'logout_confirm_title': 'Confirm Logout',
    'logout_confirm_msg': 'Are you sure you want to logout?',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'remember_me': 'Remember me',
    'learn_without_limits': 'Learn without limits',

    // Bottom Nav (Student)
    'nav_home': 'Home',
    'nav_explore': 'Explore',
    'nav_my_courses': 'My Courses',
    'nav_community': 'Community',
    'nav_profile': 'Profile',

    // Bottom Nav (Teacher)
    'nav_dashboard': 'Dashboard',
    'nav_courses': 'Courses',
    'nav_assignments': 'Tasks',
    'nav_files': 'Files',

    // Course Browser
    'browse_courses': 'Browse Courses',
    'search_courses': 'Search courses...',
    'no_courses': 'No courses available',
    'no_matching_courses': 'No matching courses',
    'enrolled': 'Enrolled',
    'students': 'students',
    'lessons': 'lessons',
    'by_teacher': 'By',

    // My Courses
    'my_learning': 'My Learning',
    'no_enrolled_courses': 'No enrolled courses yet',
    'in_progress': 'In Progress',

    // Course Detail
    'enroll': 'Enroll',
    'course_detail': 'Course Detail',

    // Profile
    'profile': 'Profile',
    'personal_info': 'Personal Info',
    'edit': 'Edit',
    'cancel': 'Cancel',
    'full_name': 'Full Name',
    'nickname': 'Nickname',
    'phone': 'Phone',
    'address': 'Address',
    'saving': 'Saving...',
    'save_changes': 'Save Changes',
    'profile_updated': 'Profile updated successfully!',
    'update_failed': 'Update failed',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_new_password': 'Confirm New Password',
    'changing': 'Changing...',
    'confirm_change_password': 'Confirm Change Password',
    'password_changed': 'Password changed successfully!',
    'fill_all_password_fields': 'Please fill in all password fields',
    'password_mismatch': 'New password and confirm password do not match',
    'field_required': 'This field is required',

    // Teacher Home
    'workspace': 'Workspace',
    'create_course': 'Create Course',
    'new_post': 'New Post',
    'latest_announcements': 'Latest Announcements',
    'income_report': 'Income Report',
    'view_earnings': 'View earnings & transactions',
    'live_settings': 'Live Settings',
    'live_title_hint': 'Live title...',
    'cover_image': 'Cover Image (optional)',
    'start_live': 'Start Live',
    'verifying_channel': 'Verifying channel...',
    'channel_ready': 'Channel is ready!',
    'recreate_channel': 'Recreate Channel?',
    'recreate_channel_msg': 'This will delete your existing channel and create a new one.\n\nOld playback URLs will no longer work.\n\nAre you sure?',
    'recreate': 'Recreate',
    'retry': 'Retry',
    'new_channel_created': 'New channel created!',
    'no_announcements': 'No announcements yet',

    // Teacher Income
    'income_trend': 'Income Trend',
    'income_breakdown': 'Income Breakdown',
    'recent_transactions': 'Recent Transactions',
    'total_income': 'Total Income',
    'records': 'records',
    'no_income_data': 'No income data yet',

    // Teacher Course Content
    'new_assignment': 'New Assignment',
    'add_new_lesson': 'Add New Lesson',
    'select_video': 'Select Video',
    'select_file': 'Select Description File',
    'file_selected': 'File Selected',
    'upload': 'Upload',
    'delete': 'Delete',
    'new_message': 'New Message',
    'post': 'Post',
    'message_posted': 'Message Posted!',
    'uploaded_successfully': 'Uploaded Successfully!',
    'deleted_successfully': 'Deleted successfully!',
    'failed_to_delete': 'Failed to delete.',
    'invalid_video_url': 'Invalid Video URL',
    'no_video_lessons': 'No video lessons yet.',
    'video_playback_options': 'Video Playback Options',
    'play_in_app': 'Play in App (Recommended)',
    'download_open': 'Download & Open (System Player)',
    'delete_lesson': 'Delete Lesson',
    'confirm_delete': 'Confirm Delete',
    'due': 'Due',

    // Assignment Management
    'manage_assignments': 'Manage Assignments',
    'select_course': 'Select Course',
    'no_assignments': 'No assignments.',
    'no_courses_found': 'No courses found.',
    'no_submissions': 'No submissions yet',
    'submissions': 'Submissions',
    'downloading': 'Downloading...',
    'error_opening_file': 'Error opening file',
    'title': 'Title',
    'description': 'Description',
    'create': 'Create',
    'submitted_on': 'Submitted',

    // Assignment Submission (Student)
    'my_tasks': 'My Tasks',
    'submitted': 'Submitted',
    'overdue': 'Overdue',
    'no_pending_tasks': 'No pending tasks! Good job.',
    'upload_solution': 'Upload Solution',
    'reupload_file': 'Re-upload File',
    'submitted_successfully': 'Submitted successfully!',
    'upload_failed': 'Upload failed. Please try again.',
    'grade': 'Grade',

    // Spin Wheel
    'lucky_wheel': 'Lucky Wheel',
    'spin_now': 'Spin Now!',
    'spinning': 'Spinning...',
    'already_spun_today': 'Already spun today!',
    'come_back_tomorrow': 'Come back tomorrow for another try!',
    'daily_limit': 'Daily limit: 1 spin',
    'spun_today': 'spun today',
    'not_spun_today': 'not yet spun today',
    'congrats': 'Congratulations!',
    'added_to_account': 'Added to your account!',
    'great': 'Great!',
    'network_error': 'Network error, please try again',

    // Tasks Page
    'daily_tasks': 'Daily Tasks',
    'daily_task_center': 'Daily Task Center',
    'daily_task_desc': 'Complete tasks every day to earn more ACoins!',
    'available_games': 'Available Games',
    'lucky_wheel_desc': 'Spin once free daily, win up to 25 ACoins!',
    'more_games': 'More Games',
    'coming_soon': 'Coming Soon',

    // Admin
    'admin_dashboard': 'Admin Dashboard',
    'role': 'Role',
    'edit_account': 'Edit Account',
    'enrolled_courses': 'Enrolled Courses',
    'no_enrollment': 'No enrolled courses',
    'update_success': 'Updated successfully!',
    'mute_duration': 'Select Mute Duration',
    'confirm_mute': 'Confirm Mute',
    'confirm_permanent_mute': 'Confirm Permanent Mute',
    'dismiss': 'Dismiss',
    'unmute': 'Unmute',
    'unmute_confirm': 'Unmute this account?',
    'confirm_unmute': 'Confirm Unmute',
    'permanent': 'Permanent',
    'days': 'days',
    'permanent_mute_warning': 'Permanent mute cannot be undone, proceed carefully',
    'announcements': 'Announcements',
    'publish_announcement': 'Publish Announcement',
    'published_announcements': 'Published Announcements',
    'posting': 'Posting...',
    'publish': 'Publish',
    'confirm_delete_title': 'Confirm Delete',
    'no_announcements_yet': 'No announcements',
    'network_err': 'Network error',

    // Common
    'loading': 'Loading...',
    'creating': 'Creating...',
    'verifying': 'Verifying...',
    'ready': 'READY',
    'new_badge': 'NEW',
    'course_name': 'Course Name',
    'unit_price': 'Unit Price',
    'total_lesson': 'Total Lessons',
    'submit': 'Submit',
    'no_file_selected': 'No file selected',

    // Feed / Community
    'community_feed': 'Community',
    'no_posts': 'No posts yet',
    'first_post': 'Be the first to post!',
    'please_login_first': 'Please login first',
    'delete_post': 'Delete Post',
    'delete_post_confirm': 'Are you sure? This cannot be undone.',
    'post_deleted': 'Post deleted',
    'reply': 'Reply',
    'comments_title': 'Comments',
    'no_comments': 'No comments yet\nBe the first to comment',
    'add_comment_hint': 'Add a comment...',
    'replying_hint': 'Replying...',
    'comment_required': 'Please enter a comment',
    'comment_posted_ok': 'Comment posted!',
    'publish_btn': 'Post',
    'replying_to_prefix': 'Replying to',
    'days_ago': 'd ago',
    'hours_ago': 'h ago',
    'minutes_ago': 'm ago',
    'just_now': 'Just now',
    'network_error_retry': 'Network error, please try again',
    'operation_failed': 'Operation failed',
    'likes_count': 'likes',
    'comments_count': 'comments',

    // Course content (teacher)
    'lesson_name': 'Lesson Name',
    'no_materials': 'No materials yet.',
    'file_options': 'File Options',
    'delete_material': 'Delete Material',
    'no_assignments_yet': 'No assignments yet.',
    'view_task_file': 'View Task File',
    'delete_task': 'Delete Task',
    'delete_message_label': 'Delete Message',
    'delete_message_confirm': 'Delete this message?',
    'no_messages': 'No messages yet.',
    'grade_saved_ok': 'Grade saved!',
    'grade_save_failed': 'Failed to save grade.',
    'save': 'Save',
    'grade_placeholder': 'Grade (e.g. A, 95)',
    'feedback_placeholder': 'Feedback',
    'assignment_created_ok': 'Assignment created!',
    'upload_error': 'Upload failed',
    'save_error': 'Save failed',

    // Register
    'student': 'Student',
    'teacher': 'Teacher',
    'fName': 'First Name',
    'nName': 'Nickname',
    'tel': 'Phone',
    'success': 'Registration successful!',

    // Misc
    'today': 'today',

    // Course Management (Teacher)
    'price_label': 'Price',
    'edit_info': 'Edit Info',
    'delete_course': 'Delete Course',
    'revenue': 'Revenue',
    'course_deleted': 'Course deleted successfully',
    'course_delete_failed': 'Failed to delete course',
    'no_courses_yet': "You haven't created any courses yet.",
    'create_course_hint': "Tap the '+' button to create one.",

        // Follow / Feed tabs
    'tab_following': 'Following',
    'tab_all': 'All',
    'avatar_all': 'All',
    'no_following': 'Not following anyone yet',
    'no_following_hint': 'Find teachers or streamers to follow,\nand see their posts here.',
    'follow': '+ Follow',
    'unfollow': 'Following',
    'stat_posts': 'Posts',
    'stat_followers': 'Followers',
    'forgot_password': 'Forgot?',
    'forgot_password_hint': 'Enter your email and we\'ll send a reset code.',
    'enter_your_email': 'your@email.com',
    'send_reset_code': 'Send Reset Code',
    'email_required': 'Please enter your email',
    'enter_reset_code': 'Enter Reset Code',
    'enter_reset_code_hint': 'Check your email and enter the code below.',
    'reset_code': 'Reset Code',
    'code_required': 'Please enter the reset code',
    'verify_code': 'Verify Code',
    'back': 'Back',
    'set_new_password': 'Set New Password',
    'set_new_password_hint': 'Enter and confirm your new password.',
    'reset_password': 'Reset Password',
    'password_reset_ok': 'Password reset successfully!',
    'email_invalid':             'Invalid email format',
    'email_not_found':           'Email not registered',
    'code_incorrect':            'Incorrect code, please try again',
    'password_required':         'Password is required',
    'password_too_short':        'Minimum 6 characters',
    'confirm_password_required': 'Please confirm your password',
  };

  // ── Traditional Chinese ────────────────────────────────────
  static const Map<String, String> _zh = {
    // App
    'app_title': 'EduLearn',
    'welcome': '歡迎回來，',
    'language': '語言',

    // Auth
    'login': '登入',
    'logout': '登出',
    'logout_confirm_title': '確認登出',
    'logout_confirm_msg': '你確定要登出嗎？',
    'register': '註冊',
    'email': '電郵',
    'password': '密碼',
    'remember_me': '記住我',
    'learn_without_limits': '無限學習',

    // Bottom Nav (Student)
    'nav_home': '首頁',
    'nav_explore': '探索',
    'nav_my_courses': '我的課程',
    'nav_community': '社群',
    'nav_profile': '個人',

    // Bottom Nav (Teacher)
    'nav_dashboard': '主頁',
    'nav_courses': '課程',
    'nav_assignments': '作業',
    'nav_files': '文件',

    // Course Browser
    'browse_courses': '瀏覽課程',
    'search_courses': '搜尋課程...',
    'no_courses': '暫無課程',
    'no_matching_courses': '找不到符合的課程',
    'enrolled': '已報名',
    'students': '名學生',
    'lessons': '堂課',
    'by_teacher': '導師：',

    // My Courses
    'my_learning': '我的學習',
    'no_enrolled_courses': '尚未報名任何課程',
    'in_progress': '進行中',

    // Course Detail
    'enroll': '立即報名',
    'course_detail': '課程詳情',

    // Profile
    'profile': '個人資料',
    'personal_info': '個人資料',
    'edit': '編輯',
    'cancel': '取消',
    'full_name': '全名',
    'nickname': '暱稱',
    'phone': '電話',
    'address': '地址',
    'saving': '儲存中...',
    'save_changes': '儲存修改',
    'profile_updated': '✅ 個人資料已更新！',
    'update_failed': '更新失敗',
    'change_password': '更改密碼',
    'current_password': '現有密碼',
    'new_password': '新密碼',
    'confirm_new_password': '確認新密碼',
    'changing': '更改中...',
    'confirm_change_password': '確認更改密碼',
    'password_changed': '✅ 密碼已成功更改！',
    'fill_all_password_fields': '請填寫所有密碼欄位',
    'password_mismatch': '新密碼與確認密碼不一致',
    'field_required': '此欄位必填',

    // Teacher Home
    'workspace': '工作區',
    'create_course': '建立課程',
    'new_post': '發布貼文',
    'latest_announcements': '最新公告',
    'income_report': '收入報表',
    'view_earnings': '查看收入及交易記錄',
    'live_settings': '直播設置',
    'live_title_hint': '直播標題...',
    'cover_image': '封面圖片（可選）',
    'start_live': '開始直播',
    'verifying_channel': '驗證頻道中...',
    'channel_ready': '頻道已就緒！',
    'recreate_channel': '重新建立頻道？',
    'recreate_channel_msg': '這將刪除你現有的頻道並建立新頻道。\n\n舊的播放連結將無法使用。\n\n確定要繼續嗎？',
    'recreate': '重新建立',
    'retry': '重試',
    'new_channel_created': '新頻道已建立！',
    'no_announcements': '暫無公告',

    // Teacher Income
    'income_trend': '收入趨勢',
    'income_breakdown': '收入分佈',
    'recent_transactions': '最近交易',
    'total_income': '總收入',
    'records': '筆記錄',
    'no_income_data': '暫無收入數據',

    // Teacher Course Content
    'new_assignment': '新增作業',
    'add_new_lesson': '新增課堂',
    'select_video': '選擇影片',
    'select_file': '選擇說明文件',
    'file_selected': '已選擇文件',
    'upload': '上傳',
    'delete': '刪除',
    'new_message': '新增留言',
    'post': '發布',
    'message_posted': '留言已發布！',
    'uploaded_successfully': '上傳成功！',
    'deleted_successfully': '刪除成功！',
    'failed_to_delete': '刪除失敗。',
    'invalid_video_url': '無效的影片連結',
    'no_video_lessons': '尚未新增影片課堂。',
    'video_playback_options': '影片播放選項',
    'play_in_app': '在應用內播放（推薦）',
    'download_open': '下載並開啟（系統播放器）',
    'delete_lesson': '刪除課堂',
    'confirm_delete': '確認刪除',
    'due': '截止日期',

    // Assignment Management
    'manage_assignments': '管理作業',
    'select_course': '選擇課程',
    'no_assignments': '暫無作業。',
    'no_courses_found': '找不到課程。',
    'no_submissions': '暫無提交',
    'submissions': '提交記錄',
    'downloading': '下載中...',
    'error_opening_file': '開啟文件時出錯',
    'title': '標題',
    'description': '描述',
    'create': '建立',
    'submitted_on': '提交日期',

    // Assignment Submission (Student)
    'my_tasks': '我的作業',
    'submitted': '已提交',
    'overdue': '已過期',
    'no_pending_tasks': '沒有待處理的作業！做得好。',
    'upload_solution': '上傳作業',
    'reupload_file': '重新上傳文件',
    'submitted_successfully': '提交成功！',
    'upload_failed': '上傳失敗，請重試。',
    'grade': '評分',

    // Spin Wheel
    'lucky_wheel': '幸運轉盤',
    'spin_now': '立即轉盤！',
    'spinning': '轉動中...',
    'already_spun_today': '今日已轉盤！',
    'come_back_tomorrow': '明天再來繼續挑戰 🎯',
    'daily_limit': '每日限轉一次',
    'spun_today': '已轉',
    'not_spun_today': '未轉',
    'congrats': '恭喜你！',
    'added_to_account': '已加入你的帳戶 🎉',
    'great': '太好了！',
    'network_error': '網絡錯誤，請重試',

    // Tasks Page
    'daily_tasks': '每日任務',
    'daily_task_center': '每日任務中心',
    'daily_task_desc': '每天完成任務，賺取更多 ACoin！',
    'available_games': '可用遊戲',
    'lucky_wheel_desc': '每日免費轉一次，最高贏 25 ACoin！',
    'more_games': '更多遊戲',
    'coming_soon': '即將推出',

    // Admin
    'admin_dashboard': '管理員後台',
    'role': '身份',
    'edit_account': '編輯帳戶資料',
    'enrolled_courses': '已報名課程',
    'no_enrollment': '無報名紀錄',
    'update_success': '更新成功！',
    'mute_duration': '選擇禁言時長',
    'confirm_mute': '確認禁言',
    'confirm_permanent_mute': '確認永久禁言',
    'dismiss': '駁回',
    'unmute': '解除禁言',
    'unmute_confirm': '確定要解除以下帳號的全域禁言嗎？',
    'confirm_unmute': '確認解除',
    'permanent': '永久',
    'days': '天',
    'permanent_mute_warning': '永久禁言無法撤回，請謹慎操作',
    'announcements': '最新公告',
    'publish_announcement': '發布新消息',
    'published_announcements': '已發布消息',
    'posting': '發布中...',
    'publish': '發布消息',
    'confirm_delete_title': '確認刪除',
    'no_announcements_yet': '暫無消息',
    'network_err': '網絡錯誤',

    // Common
    'loading': '載入中...',
    'creating': '建立中...',
    'verifying': '驗證中...',
    'ready': '就緒',
    'new_badge': '新',
    'course_name': '課程名稱',
    'unit_price': '單價',
    'total_lesson': '課堂總數',
    'submit': '提交',
    'no_file_selected': '未選擇文件',

    // Feed / Community
    'community_feed': '社群動態',
    'no_posts': '暫無貼文',
    'first_post': '快來發布第一篇貼文吧！',
    'please_login_first': '請先登入',
    'delete_post': '刪除貼文',
    'delete_post_confirm': '確定要刪除這篇貼文嗎？此操作無法復原。',
    'post_deleted': '貼文已刪除',
    'reply': '回覆',
    'comments_title': '評論',
    'no_comments': '尚無評論\n成為第一個留言的人',
    'add_comment_hint': '新增評論...',
    'replying_hint': '回覆中...',
    'comment_required': '請輸入評論內容',
    'comment_posted_ok': '評論發布成功！',
    'publish_btn': '發佈',
    'replying_to_prefix': '正在回覆',
    'days_ago': '天前',
    'hours_ago': '小時前',
    'minutes_ago': '分鐘前',
    'just_now': '剛剛',
    'network_error_retry': '網路錯誤，請稍後再試',
    'operation_failed': '操作失敗',
    'likes_count': '次讚',
    'comments_count': '則評論',

    // Course content (teacher)
    'lesson_name': '課堂名稱',
    'no_materials': '尚無材料。',
    'file_options': '文件選項',
    'delete_material': '刪除材料',
    'no_assignments_yet': '尚無作業。',
    'view_task_file': '查看作業文件',
    'delete_task': '刪除作業',
    'delete_message_label': '刪除留言',
    'delete_message_confirm': '確定要刪除此留言嗎？',
    'no_messages': '尚無留言。',
    'grade_saved_ok': '評分已儲存！',
    'grade_save_failed': '儲存評分失敗。',
    'save': '儲存',
    'grade_placeholder': '評分 (例: A, 95)',
    'feedback_placeholder': '意見',
    'assignment_created_ok': '作業已建立！',
    'upload_error': '上傳失敗',
    'save_error': '儲存失敗',

    // Register
    'student': '學生',
    'teacher': '老師',
    'fName': '全名',
    'nName': '暱稱',
    'tel': '電話',
    'success': '註冊成功！',

    // Misc
    'today': '今日',

    // Course Management (Teacher)
    'price_label': '價格',
    'edit_info': '編輯資料',
    'delete_course': '刪除課程',
    'revenue': '收入',
    'course_deleted': '課程已成功刪除',
    'course_delete_failed': '刪除課程失敗',
    'no_courses_yet': '尚未建立任何課程。',
    'create_course_hint': '點擊「+」按鈕建立課程。',
    
        // Follow / Feed tabs
    'tab_following': '關注',
    'tab_all': '所有動態',
    'avatar_all': '全部',
    'no_following': '還沒有關注任何人',
    'no_following_hint': '去發現你感興趣的老師或主播，\n在這裡就能看到他們的動態。',
    'follow': '+ 關注',
    'unfollow': '已關注',
    'stat_posts': '貼文',
    'stat_followers': '粉絲',
    'forgot_password': '忘記密碼',
    'forgot_password_hint': '輸入你的電郵，我們將發送重置碼。',
    'enter_your_email': '你的電郵地址',
    'send_reset_code': '發送重置碼',
    'email_required': '請輸入電郵',
    'enter_reset_code': '輸入重置碼',
    'enter_reset_code_hint': '請查看你的電郵並輸入以下重置碼。',
    'reset_code': '重置碼',
    'code_required': '請輸入重置碼',
    'verify_code': '驗證',
    'back': '返回',
    'set_new_password': '設定新密碼',
    'set_new_password_hint': '請輸入並確認你的新密碼。',
    'reset_password': '重置密碼',
    'password_reset_ok': '密碼已成功重置！',
    // Reset Password errors
    'email_invalid':             '電郵格式不正確',
    'email_not_found':           '此電郵尚未註冊',
    'code_incorrect':            '重置碼錯誤，請重試',
    'password_required':         '請輸入密碼',
    'password_too_short':        '密碼最少 6 位',
    'confirm_password_required': '請確認密碼',
  };
}
